### ISSUE TITLE
Configure #all support on/off

### ISSUE THREAD

**Issue by Russell-Allen** [openziti/edge#763]
#all is a powerful attribute that makes policy configuration easy in most networks.  As they say, "with great power ..." (you know the rest, right?)

In some networks, particularly those with multiple administrators, the use of `#all` as a policy attribute might lead to unexpected consequences simply because one administrator isn't aware of the actions of another.  While that kind of mistake is possible with any attribute, the `#all` attribute's magic behavior invites unintended side effects.

I propose that a network can be statically configured (ie, this is _not_ a management API setting) to support `#all` in its current magical meaning, or that behavior can be turned off.  I would assume that a network with no configuration setting one way or the other would default to `#all` support on so that existing network configurations remain backwards compatible.  I don't have a strong opinion with regard to the treatment of `#all` when support is turned off ... ie, whether it is treated as any other attribute or it is treated as a reserved word that is not allowed when configured off.

**Comment by plorenz** [comment]
I was thinking about this and I don't think we want to change the semantic of `#all` based on a flag. If the flag gets changed, now we'd have to recalculate all the policies, and we wouldn't necessarily know that the flag has changed in order to do that calculation. Which means we might have to store the flag in the DB, introducing a new global/persistent configuration system, which seems like overkill.

What might be reasonable would be to just disallow using `#all`, since that doesn't have semantic implications. However, wouldn't it be just as easy to implement that in a higher layer?

**Comment by Russell-Allen** [comment]
I'm inferring from "we'd have to recalculate all the policies" that the policies are persisted in the db.  In that case ... yeah, dynamic recalculation sounds like a bad idea to me too.

When you say "just disallow using `#all`" ... do you mean removing the special treatment of `#all` completely; not just by configuration?  If so, I think that's overkill the other direction.  `#all` is a frequently used, very handy feature.

Now that I understand the implications better, you won't hurt my feelings by closing this feature request.  :)  And to answer your question, yes, a higher 'management layer' could do this with less risk/work that what I now understand would be required to do it in Ziti.  :+1:

**Comment by plorenz** [comment]
By "Disallow `#all`" I meant a config flag that would prevent users from using `#all`, but wouldn't change any evaluation logic. Since you don't see any issues doing this at a higher level, I'll close this out :+1:
